from __future__ import annotations
from formatter import Layout, LayoutField, FieldType

ANEXO07_C170 = Layout(
    name="ANEXO 07 – C170 (Produtos)",
    fields=[
        LayoutField("num_item_nf", FieldType.I, default=0),
        LayoutField("cod_prod", FieldType.A, default=""),
        LayoutField("tipo_mov", FieldType.A, default="E"),
        LayoutField("cnpj_cpf_cliente", FieldType.A, default=""),
        LayoutField("ie_cliente", FieldType.I, default=0),
        LayoutField("num_nf", FieldType.I, default=0),
        LayoutField("data_nf", FieldType.A, default=""),
        LayoutField("uf_nf", FieldType.A, default=""),
        LayoutField("serie_nf", FieldType.A, default="1"),
        LayoutField("especie_nf", FieldType.A, default="NF"),
        LayoutField("modelo_nf", FieldType.I, default=55),
        LayoutField("qtd_total_item", FieldType.N, decimals=2, default=0),
        LayoutField("valor_total_item", FieldType.N, decimals=2, default=0),
        LayoutField("aliq_icms", FieldType.N, decimals=2, default=0),
        LayoutField("valor_ipi", FieldType.N, decimals=2, default=0),
        LayoutField("bc_icms", FieldType.N, decimals=2, default=0),
        LayoutField("bc_st", FieldType.N, decimals=2, default=0),
        LayoutField("valor_desc", FieldType.N, decimals=2, default=0),
        LayoutField("cfop", FieldType.A, default=""),
        LayoutField("cst_icms", FieldType.A, default=""),
        LayoutField("mov_fisica", FieldType.L, default=True),
        LayoutField("cst_cofins", FieldType.I, default=1),
        LayoutField("cst_pis", FieldType.I, default=1),
        LayoutField("cst_ipi", FieldType.I, default=1),
        LayoutField("aliq_ipi", FieldType.N, decimals=2, default=0),
        LayoutField("bc_ipi", FieldType.N, decimals=2, default=0),
        LayoutField("aliq_pis", FieldType.N, decimals=2, default=0),
        LayoutField("bc_pis", FieldType.N, decimals=2, default=0),
        LayoutField("valor_pis", FieldType.N, decimals=2, default=0),
        LayoutField("aliq_cofins", FieldType.N, decimals=2, default=0),
        LayoutField("bc_cofins", FieldType.N, decimals=2, default=0),
        LayoutField("valor_cofins", FieldType.N, decimals=2, default=0),
        LayoutField("valor_icms", FieldType.N, decimals=2, default=0),
        LayoutField("aliq_st", FieldType.N, decimals=2, default=0),
        LayoutField("valor_st", FieldType.N, decimals=2, default=0),
    ],
)

ANEXO09_ENTRADAS = Layout(
    name="ANEXO 09 – Entradas",
    fields=[
        LayoutField("chave_import", FieldType.I, default=1),
        LayoutField("cnpj_cpf_cliente", FieldType.A, default=""),
        LayoutField("uf_emit", FieldType.A, default=""),
        LayoutField("data_entrada", FieldType.A, default=""),
        LayoutField("data_emissao", FieldType.A, default=""),
        LayoutField("num_nf", FieldType.I, default=0),
        LayoutField("especie_doc", FieldType.A, default="NF"),
        LayoutField("serie", FieldType.A, default="1"),
        LayoutField("nat_oper", FieldType.A, default=""),
        LayoutField("valor_contabil", FieldType.N, decimals=2, default=0),
        LayoutField("origem_merc", FieldType.A, default="0"),
        LayoutField("cst_icms", FieldType.A, default="00"),
        LayoutField("red_bc_icms", FieldType.N, decimals=4, default=0),
        LayoutField("bc_icms", FieldType.N, decimals=2, default=0),
        LayoutField("aliq_icms", FieldType.N, decimals=4, default=0),
        LayoutField("valor_icms", FieldType.N, decimals=2, default=0),
        LayoutField("isentas_icms", FieldType.N, decimals=2, default=0),
        LayoutField("outras_icms", FieldType.N, decimals=2, default=0),
        LayoutField("icms_st_flag", FieldType.A, default="N"),
        LayoutField("bc_icms_st", FieldType.N, decimals=2, default=0),
        LayoutField("aliq_icms_st", FieldType.N, decimals=4, default=0),
        LayoutField("valor_icms_st", FieldType.N, decimals=2, default=0),
        LayoutField("bc_ipi", FieldType.N, decimals=2, default=0),
        LayoutField("valor_ipi", FieldType.N, decimals=2, default=0),
    ],
)

ANEXO04_SAIDAS = Layout(
    name="ANEXO 04 – Saídas",
    fields=[
        LayoutField("chave_import", FieldType.I, default=1),
        LayoutField("cnpj_cpf_cliente", FieldType.A, default=""),
        LayoutField("uf_emit", FieldType.A, default=""),
        LayoutField("data_saida", FieldType.A, default=""),
        LayoutField("data_emissao", FieldType.A, default=""),
        LayoutField("num_nf", FieldType.I, default=0),
        LayoutField("especie_doc", FieldType.A, default="NF"),
        LayoutField("serie", FieldType.A, default="1"),
        LayoutField("nat_oper", FieldType.A, default=""),
        LayoutField("valor_contabil", FieldType.N, decimals=2, default=0),
        LayoutField("cst_icms", FieldType.A, default="00"),
        LayoutField("bc_icms", FieldType.N, decimals=2, default=0),
        LayoutField("aliq_icms", FieldType.N, decimals=2, default=0),
        LayoutField("valor_icms", FieldType.N, decimals=2, default=0),
        LayoutField("valor_ipi", FieldType.N, decimals=2, default=0),
        LayoutField("valor_frete", FieldType.N, decimals=2, default=0),
        LayoutField("valor_seg", FieldType.N, decimals=2, default=0),
        LayoutField("valor_outras", FieldType.N, decimals=2, default=0),
    ],
)